var files = {
	"webgl": [
		"webgl_camera",
		"webgl_camera_array",
		"webgl_camera_cinematic",
		"webgl_camera_logarithmicdepthbuffer",
		"webgl_depth_texture",
		"webgl_lightprobe",
		"webgl_lightprobe_cubecamera",
		"webgl_lights_hemisphere",
		"webgl_lights_physical",
		"webgl_lights_pointlights",
		"webgl_lights_pointlights2",
		"webgl_lights_spotlight",
		"webgl_lights_spotlights",
		"webgl_lights_rectarealight",
		"webgl_loader_3ds",
		"webgl_loader_3mf",
		"webgl_loader_3mf_materials",
		"webgl_loader_amf",
		"webgl_loader_assimp",
		"webgl_loader_bvh",
		"webgl_loader_collada",
		"webgl_loader_collada_kinematics",
		"webgl_loader_collada_skinning",
		"webgl_loader_draco",
		"webgl_loader_fbx",
		"webgl_loader_fbx_nurbs",
		"webgl_loader_gcode",
		"webgl_loader_kmz",
		"webgl_loader_ldraw",
		"webgl_loader_lwo",
		"webgl_loader_obj",
		"webgl_loader_obj_mtl",
		"webgl_loader_obj2",
		"webgl_loader_obj2_options",
		"webgl_loader_ply",
		"webgl_loader_prwm",
		"webgl_loader_stl",
		"webgl_loader_svg",
		"webgl_loader_texture_basis",
		"webgl_loader_ttf",
		"webgl_loader_vrm",
		"webgl_loader_vrml",
		"webgl_loader_vtk",
		"webgl_materials",
		"webgl_materials_blending",
		"webgl_materials_blending_custom",
		"webgl_materials_channels",
		"webgl_modifier_simplifier",
		"webgl_multiple_elements",
		"webgl_multiple_views",
		"webgl_shadowmap_viewer",
		"webgl_shadowmap_vsm",
		"webgl_shadowmesh",
	],
	"misc": [
		"misc_controls_drag",
		"misc_controls_trackball",
		"misc_controls_transform",
		"misc_exporter_collada",
		"misc_exporter_draco",
		"misc_exporter_gltf",
		"misc_exporter_obj",
		"misc_exporter_ply",
		"misc_exporter_stl",
		"misc_lookat",
	]
};

var tags = {
	"webgl_animation_cloth": [ "physics", "integration" ],
	"webgl_clipping": [ "solid" ],
	"webgl_clipping_advanced": [ "solid" ],
	"webgl_clipping_intersection": [ "solid" ],
	"webgl_clipping_stencil": [ "solid" ],
	"webgl_decals": [ "normals" ],
	"webgl_depth_texture": [ "renderTarget" ],
	"webgl_framebuffer_texture": [ "renderTarget" ],
	"webgl_geometry_colors_lookuptable": [ "vertex" ],
	"webgl_geometry_hierarchy": [ "group" ],
	"webgl_geometry_hierarchy2": [ "scene graph" ],
	"webgl_geometry_minecraft_ao": [ "ambient occlusion" ],
	"webgl_geometry_nurbs": [ "curve", "surface" ],
	"webgl_geometry_spline_editor": [ "curve" ],
	"webgl_geometry_text": [ "font" ],
	"webgl_geometry_text_shapes": [ "font" ],
	"webgl_geometry_text_stroke": [ "font" ],
	"webgl_helpers": [ "normals", "tangents", "bounding box" ],
	"webgl_instancing_performance": [ "batching", "merging" ],
	"webgl_interactive_buffergeometry": [ "raycast", "outline" ],
	"webgl_interactive_cubes": [ "raycast", "highlinght" ],
	"webgl_interactive_cubes_gpu": [ "raycast", "highlight" ],
	"webgl_interactive_cubes_ortho": [ "raycast", "highlight" ],
	"webgl_interactive_lines": [ "raycast" ],
	"webgl_interactive_points": [ "raycast" ],
	"webgl_interactive_raycasting_points": [ "raycast" ],
	"webgl_interactive_voxelpainter": [ "raycast" ],
	"webgl_layers": [ "groups" ],
	"webgl_lights_hemisphere": [ "directional" ],
	"webgl_lights_pointlights": [ "multiple" ],
	"webgl_loader_ttf": [ "text", "font" ],
	"webgl_loader_pdb": [ "molecules" ],
	"webgl_lod": [ "level", "details" ],
	"webgl_materials_blending": [ "alpha" ],
	"webgl_materials_blending_custom": [ "alpha" ],
	"webgl_materials_channels": [ "normal", "depth", "rgba packing" ],
	"webgl_materials_cubemap_mipmaps": [ "envmap" ],
	"webgl_materials_envmaps_parallax": [ "onBeforeCompile" ],
	"webgl_materials_lightmap": [ "shadows" ],
	"webgl_materials_physical_clearcoat": [ "anisotropy" ],
	"webgl_materials_physical_transparency": [ "alpha" ],
	"webgl_materials_shaders_fresnel": [ "refraction" ],
	"webgl_materials_standard": [ "pbr" ],
	"webgl_materials_texture_canvas": [ "paint" ],
	"webgl_materials_texture_filters": [ "mipmap", "min", "mag" ],
	"webgl_materials_texture_manualmipmap": [ "mipmap", "min", "mag" ],
	"webgl_materials_subsurface_scattering": [ "derivatives", "translucency" ],
	"webgl_materials_wireframe": [ "derivatives" ],
	"webgl_math_obb": [ "intersection", "bounding" ],
	"webgl_math_orientation_transform": [ "rotation" ],
	"webgl_mirror": [ "reflection" ],
	"webgl_morphtargets_horse": [ "animation" ],
	"webgl_multiple_elements": [ "differential equations", "physics" ],
	"webgl_multiple_elements_text": [ "font" ],
	"webgl_nearestneighbour": [ "kdtree" ],
	"webgl_panorama_cube": [ "envmap" ],
	"webgl_panorama_equirectangular": [ "envmap" ],
	"webgl_points_billboards": [ "particles" ],
	"webgl_points_dynamic": [ "particles" ],
	"webgl_points_sprites": [ "particles", "snow" ],
	"webgl_points_waves": [ "particles" ],
	"webgl_read_float_buffer": [ "texture" ],
	"webgl_refraction": [ "water" ],
	"webgl_rtt": [ "renderTarget", "texture" ],
	"webgl_shaders_ocean": [ "water" ],
	"webgl_shaders_ocean2": [ "water" ],
	"webgl_shaders_sky": [ "sun" ],
	"webgl_shaders_tonemapping": [ "hrd" ],
	"webgl_shaders_vector": [ "font" ],
	"webgl_shading_physical": [ "pbr" ],
	"webgl_shadow_contact": [ "onBeforeCompile", "soft" ],
	"webgl_shadowmap_viewer": [ "directional", "spot" ],
	"webgl_skinning_simple": [ "animation" ],
	"webgl_tonemapping": [ "gltf" ],
	"webgl_loader_nodes": [ "caustics", "displace", "xray" ],
	"webgl_postprocessing_afterimage": [ "trails" ],
	"webgl_postprocessing_dof": [ "bokeh" ],
	"webgl_postprocessing_dof2": [ "bokeh" ],
	"webgl_postprocessing_fxaa": [ "msaa", "multisampled" ],
	"webgl_postprocessing_godrays": [ "light scattering" ],
	"webgl_postprocessing_ssaa": [ "msaa", "multisampled" ],
	"webgl_postprocessing_ssaa_unbiased": [ "msaa", "multisampled" ],
	"webgl_postprocessing_sao": [ "ambient occlusion" ],
	"webgl_postprocessing_smaa": [ "msaa", "multisampled" ],
	"webgl_postprocessing_sobel": [ "filter", "edge detection" ],
	"webgl_postprocessing_ssao": [ "ambient occlusion" ],
	"webgl_postprocessing_unreal_bloom": [ "glow" ],
	"webgl_postprocessing_unreal_bloom_selective": [ "glow" ],
	"webgl_fire": [ "smoke" ],
	"webgl_materials_modified": [ "onBeforeCompile" ],
	"webgl_shadowmap_csm": [ "cascade" ],
	"webgl_shadowmap_pcss": [ "soft" ],
	"webgl_simple_gi": [ "global illumination" ],
	"webgl_tiled_forward": [ "derivatives" ],
	"webgl2_multisampled_renderbuffers": [ "msaa" ],
	"physics_ammo_cloth": [ "integration" ],
	"misc_controls_deviceorientation": [ "accelerometer", "sensors" ],
	"misc_controls_drag": [ "translate" ],
	"misc_controls_map": [ "drag" ],
	"misc_controls_orbit": [ "rotation" ],
	"misc_controls_trackball": [ "rotation" ],
	"misc_controls_transform": [ "scale", "rotate", "translate" ]
};
